# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  # pull_request:  //TODO: pull request, just test
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: cypress-io/github-action@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: NODE_ENV=test npm ci
    - run: npm run test:coverage
    - run: npm run coverage:upload
    - run: NODE_ENV=production npm run build
      env:
        REACT_APP_FIREBASE_apiKey: ${{ secrets.REACT_APP_FIREBASE_apiKey }}
        REACT_APP_FIREBASE_authDomain: ${{ secrets.REACT_APP_FIREBASE_authDomain }}
        REACT_APP_FIREBASE_databaseURL: ${{ secrets.REACT_APP_FIREBASE_databaseURL }}
        REACT_APP_FIREBASE_projectId: ${{ secrets.REACT_APP_FIREBASE_projectId }}
        REACT_APP_FIREBASE_storageBucket: ${{ secrets.REACT_APP_FIREBASE_storageBucket }}
        REACT_APP_FIREBASE_messagingSenderId: ${{ secrets.REACT_APP_FIREBASE_messagingSenderId }}
        REACT_APP_FIREBASE_appId: ${{ secrets.REACT_APP_FIREBASE_appId }}
        REACT_APP_FIREBASE_measurementId: ${{ secrets.REACT_APP_FIREBASE_measurementId }}
    - name: Upload Build Directory
      uses: up9cloud/action-rsync@v1.2
      env:
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_KEY }}
        TARGET: ${{ secrets.SSH_BUILD_PATH }}
        VERBOSE: true
        USER: ${{ secrets.SSH_USER }}
        # PORT: 2222 # no need to set this, because of $SSH_ARGS
        ARGS: -az --exclude=/.git/
        SSH_ARGS: '-p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
        SOURCE: ./build/
        PRE_SCRIPT: |
            echo start at:
            date -u --rfc-3339=ns
        POST_SCRIPT: "echo done at: && date -u --rfc-3339=ns"
    - name: Upload Public Directory
      uses: up9cloud/action-rsync@v1.2
      env:
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_KEY }}
        TARGET: ${{ secrets.SSH_PUBLIC_PATH }}
        VERBOSE: true
        USER: ${{ secrets.SSH_USER }}
        PORT: 22
        ARGS: -az --exclude=/.git/
        SOURCE: ./public/
        PRE_SCRIPT: |
            echo start at:
            date -u --rfc-3339=ns
        POST_SCRIPT: "echo done at: && date -u --rfc-3339=ns"